[package]
name = "serde-redis"
version = "0.1.1"
authors = ["Joe Wilm <joe@jwilm.com>"]
description = "Serde deserialization for redis-rs"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/one-signal/serde-redis"
documentation = "https://one-signal.github.io/serde-redis/serde_redis/"

[dependencies]
redis = "0.5"
serde = "0.7"
serde_macros = "0.7"
