[package]
name = "serde-redis"
version = "0.6.0"
authors = ["Joe Wilm <joe@jwilm.com>"]
description = "Serde deserialization for redis-rs"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/one-signal/serde-redis"
documentation = "https://one-signal.github.io/serde-redis/serde_redis/"

[dependencies]
redis = "> 0.5, < 0.9"
serde = "0.9"

[dev-dependencies]
serde_derive = "0.9"
