[package]
name = "redis-serde"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]

[dependencies]
redis = "0.5"

[dependencies.serde]
git = "https://github.com/serde-rs/serde"
rev = "b3212f4c2bf91adc7767eabeb75cfc6369d4dcf6"

[dependencies.serde_macros]
git = "https://github.com/serde-rs/serde"
rev = "b3212f4c2bf91adc7767eabeb75cfc6369d4dcf6"
